config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    registrations: 'users',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  post "/messages/forward", to: "messages#incoming", as: :email_processor

  get "about", to: "home#about", as: :about
  get "confirm", to: "home#confirm", as: :confirm
  get "privacy-policy", to: "home#privacy_policy", as: :privacy_policy
  get "terms", to: "home#terms", as: :terms_of_service
  devise_scope :user do
    get "match-preference", to: "users#match_preference", as: :match_preference
    get "update-match-preference", to: "users#update_match_preference", as: :update_match_preference
    get '/users/:id/finish_signup',  to: 'users#finish_signup', as: :finish_signup
  end
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :async, :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates :email, email_format: {message: "please enter a valid email."}
  validate :unique_email
  validate :not_burner_email
  validates :desired_candidate, presence: true, allow_blank: false
  validate :valid_phone, if: :phone?
  after_validation :report_validation_errors_to_rollbar

  belongs_to :match, class_name: "User", optional: true
  belongs_to :us_state, class_name: "State", foreign_key: "state", primary_key: "short_name"
  has_many :identities, dependent: :destroy

  def self.in_swing_state
    joins(:us_state).merge(State.swing)
  end

  def self.in_safe_state
    joins(:us_state).merge(State.uncontested)
  end

  def self.clinton
    where(desired_candidate: CLINTON)
  end

  def self.third_party
    where(desired_candidate: [STEIN, JOHNSON, MCMULLIN])
  end

  def self.unmatched
    where(match_id: nil)
  end

  def self.matched
    where("match_id IS NOT NULL")
  end

  def self.confirmed
    where("confirmed_at IS NOT NULL")
  end

  def self.unconfirmed
    where(confirmed_at: nil)
  end

  def self.unmatched_swing
    unmatched.in_swing_state.third_party.confirmed
  end

  def self.unmatched_safe
    unmatched.in_safe_state.clinton.confirmed
  end

  def matched?
    match_id?
  end

  def clinton_voter?
    desired_candidate == CLINTON
  end

  def safe_state?
    !us_state.swing?
  end

  # Internally store phone numbers as numbers
  def phone=(num)
    num.gsub!(/\D/, '')
    super(num)
  end

  def match_preference=(array)
    array = Array(array)
    super(array.reject(&:blank?))
  end

  def match_with(user)
    return if user.blank? || user.match_id? || self.match_id?

    user.match = self
    self.match = user
    saved = true
    User.transaction do
      saved = saved && self.save
      saved = saved && user.save
      unless saved
        raise ActiveRecord::Rollback, "setting match_id failed"
      end
    end
    if saved
      user.notify_matched
      self.notify_matched
    end
    saved
  end

  def anonymized_email
    "#{name} <connect+#{uuid}@#{ENV['MAIL_DOMAIN']}>"
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
          state: TEMP_STATE,
          desired_candidate: TEMP_CANDIDATE
        )
        user.skip_confirmation! if email_is_verified
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def default_social_email?
    self.email && self.email.match(TEMP_EMAIL_REGEX)
  end

  def default_social_data?
    state == TEMP_STATE || state == TEMP_CANDIDATE || default_social_email?
  end

  def display_email
    email unless default_social_email?
  end

  def find_a_match
    return if match_id?

    if clinton_voter? && safe_state?
      if match_preference
        if match_preference == "No Preference" || match_preference == [""] || match_preference.blank?
          swing_voter = User.confirmed.unmatched.in_swing_state.third_party.first
        else
          swing_voter = User.confirmed.unmatched.in_swing_state.where(desired_candidate: match_preference).first
        end
        match_with swing_voter
      end
    end
  end

  def notify_matched
    MailerJob.perform_later "UserMailer", "notify_matched", self
  end

  def send_trump_trader_email
    #MailerJob.perform_later "UserMailer", "trump_trader", self
    UserMailer.trump_trader self
  end

  def burner_emails
    Rails.cache.fetch("burner-emails") { open("https://raw.githubusercontent.com/andreis/disposable/master/domains.txt").read }
  end

  private

  def unique_email
    if term = email.match(/.*\+/)
      term = "#{term[0]}%"
      if user = User.where("email LIKE ?", term).last
        if user != self
          errors.add :email, "has been taken."
        end
      end
    end
  end

  def not_burner_email
    return unless email?

    addr = Mail::Address.new(email)
    if burner_emails.match Regexp.new("^#{addr.domain}")
      errors.add :email, "cannot be a temporary address."
    end
  end

  def valid_phone
    if phone.length == 10 || (phone.length == 11 && phone[0] == '1')
      # phone is valid
    else
      errors.add :phone, "is invalid."
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  protected
  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    puts "foo"
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create, :update]
  before_action :authenticate_scope!, only: [:match_preference, :update_match_preference, :edit, :update, :destroy]

  # a special case edit page, only for HRC users
  def match_preference
  end

  def update_match_preference
    pref = params[:pref]
    if ["No Preference", "Jill Stein", "Gary Johnson", "Evan McMullin"].include? pref
      if current_user.update_attribute :match_preference, pref
        if current_user.find_a_match
          redirect_to root_path, notice: "Preference recorded!"
        else
          redirect_to match_preference_path, error: "Preference recorded!"
        end
      else
        redirect_to match_preference_path, error: "Something went wrong, please try again."
      end
    else
      redirect_to match_preference_path, error: "Something went wrong, please try again."
    end
  end

  def login_type
  end

  # GET /users/:id/finish_signup
  # a special case edit page
  def finish_signup
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:state, :desired_candidate, :phone, :email, :name)
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    if params[:password].present? || params[:current_password].present? || params[:password_confirmation].present?
      resource.update_with_password(params)
    else
      params.delete :password
      params.delete :current_password
      params.delete :password_confirmation
      resource.update_attributes(params)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:state, :desired_candidate, :name, :phone])
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit :current_password,
        :desired_candidate,
        :email,
        :match_strict,
        :name,
        :password,
        :password_confirmation,
        :phone,
        :state,
        match_preference: []
    end
  end

  def after_sign_up_path_for(user)
    flash[:registered] = true
    if user.clinton_voter? && user.safe_state?
      match_preference_path
    else
      confirm_path
    end
  end
end

app/views/users/_match_preference_fields.html.haml
.row
  .columns.small-12.medium-6
    = f.label :match_preference do
      Match Preference
      = f.select :match_preference, ["No Preference", "Jill Stein", "Gary Johnson", "Evan McMullin"], {include_hidden: false}, multiple: true
.row
  .columns.small-12.medium-6
    = f.label :match_strict do
      = f.check_box :match_strict, {}, "aria-describedby" => "strictHelp"
      Require match with preferred 3rd Party?
    %p.help-text.color-dark-gray#strictHelp
      If you check this box, you will not be matched with a 3rd-party voter in a swing state unless there is an available
      voter with your preferred party.

app/views/users/finish_signup.html.haml
.row.columns.content
  %h1 Finish Your Registration
  = form_for(@user, url: registration_path(:user)) do |f|
    - if @user.errors.any?
      .row
        .columns.small-12
          = devise_error_messages!
    .row
      .columns.small-12.medium-6
        = f.label :name do
          Name
          = f.text_field :name, autofocus: true, placeholder: "Steve H, mr robot, Mz Green, etc", "aria-describedby" => "nameHelp"
        %p.help-text#nameHelp This will be public, how you are identified on the site.

      - if @user.default_social_email?
        .columns.small-12.medium-6
          = f.label :email do
            Email
            = f.email_field :email, "aria-describedby" => "emailHelp", value: @user.display_email
          %p.help-text#emailHelp This will be private. And we will never spam you or sell your info.

    .row.callout.primary
      .columns.small-12.medium-6
        = f.label :state do
          State
          = f.select :state, State.for_select

      .columns.small-12.medium-6
        = f.label :desired_candidate do
          Who did you want to vote for?
          = f.select :desired_candidate, candidates, prompt: "Choose a Candidate"

    .row.actions
      .columns.small-12
        = f.submit "Finish Signup", class: "button primary radius large expanded", "aria-describedby" => "submitHelp"
        %p.text-center.help-text#submitHelp
          By clicking "Finish Signup" you agree to our #{link_to "Terms of Service", terms_of_service_path}.

app/views/users/match_preference.html.haml
.row.columns.content
  %h2 Match Preference

  .row
    .columns.small-12.medium-8.large-6.callout.primary
      What kind of 3rd-party voter would you like to be paired with?

  = form_for(current_user, url: registration_path(:user), method: :put) do |f|
    = render "match_preference_fields", f: f

    .row.actions
      .columns.small-12.medium-6
        = f.submit "Save Preference", class: "button primary large right"