config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    registrations: 'users',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  post "/messages/forward", to: "messages#incoming", as: :email_processor

  get "about", to: "home#about", as: :about
  get "confirm", to: "home#confirm", as: :confirm
  get "privacy-policy", to: "home#privacy_policy", as: :privacy_policy
  get "terms", to: "home#terms", as: :terms_of_service
  devise_scope :user do
    get "match-preference", to: "users#match_preference", as: :match_preference
    get "update-match-preference", to: "users#update_match_preference", as: :update_match_preference
    get '/users/:id/finish_signup',  to: 'users#finish_signup', as: :finish_signup
  end
  root to: "home#index"
end

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= @page_title || "Make Mine Count"

    %link(href="https://fonts.googleapis.com/css?family=Roboto:400,900" rel="stylesheet")
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor", "application", "data-turbolinks-track" => "reload"
    = csrf_meta_tags

    %meta(property="fb:app_id" content="173652306389327")
    %meta(property="og:type" content="article")
    %meta(property="og:url" content="#{request.original_url}")
    %meta(property="og:title" content="Make Mine Count")
    %meta(property="og:image" content="#{image_url 'hero-combined.jpg'}")
    %meta(property="og:image:width" content="1500")
    %meta(property="og:image:height" content="989")
    %meta(property="og:description" content="Using strategic vote—swapping to simultaneously defeat Trump while supporting third parties.")

    - if Rails.env.production?
      -# Facebook Pixel Code
      :javascript
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');

        fbq('init', '1624610904503851');
        fbq('track', "PageView");
      %noscript
        %img(height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=668391199985087&ev=PageView&noscript=1")
      -# End Facebook Pixel Code

      -# r4c16 Twitter tracking code
      :javascript
        !function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
        },s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
        a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
        // Insert Twitter Pixel ID and Standard Event data below
        twq('init','nvim1');
        twq('track','PageView');
      -# end twitter tracking

    - if ENV["GOOGLE_ANALYTICS"].present?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', '#{ENV["GOOGLE_ANALYTICS"]}', 'auto');

  %body
    #fb-root
    .top-bar
      .row.columns
        = link_to root_path do
          = image_tag "logo.png", class: "logo"
        %ul.menu.dropdown.right(data-dropdown-menu data-click-open="true" data-disable-hover="true")
          - if user_signed_in?
            %li.is-dropdown-submenu-parent
              = link_to current_user.name, "#"
              %ul.menu
                %li= link_to "Account", edit_user_registration_path
                %li= link_to "Sign Out", destroy_user_session_path
          - else
            %li= link_to "Count Me In!", new_user_registration_path, class: "button hide-for-small-only"

    -# flash notifications
    - alert_mappings = {"info" => "primary", "notice" => "primary", "error" => "alert", "alert" => "alert"}
    - flash.each do |k, v|
      - next unless alert_mappings[k].present?
      .callout{class: [alert_mappings[k], k], data: {closable: true}}
        = v
        %button.close-button(aria-label="Dismiss alert" type="button" data-close)
          %span(aria-hidden="true") &times;

    = yield

    .text-center.margin-top-4
      .display-inline-block.callout.color-dark-gray
        NOT AUTHORIZED BY ANY CANDIDATE OR CANDIDATE'S COMMITTEE
    .menu-centered
      %ul.menu
        %li.menu-text= link_to "Tweet", "https://twitter.com/intent/tweet?#{tweet_params.to_query}", class: "twitter-share-button", data: {size: "large"}
        %li.menu-text
          .fb-share-button(data-href="https://www.makeminecount.org" data-layout="button" data-size="large" data-mobile-iframe="true")
            = link_to "Share", "https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.makeminecount.org%2F&amp;src=sdkpreparse", class: "fb-xfbml-parse-ignore", target: "_blank"
    .menu-centered
      %ul.menu
        %li= link_to "About", about_path
        %li= link_to "Privacy Policy", privacy_policy_path
        %li= link_to "Terms of Service", terms_of_service_path